name: Bot Diario Violeta

on:
  schedule:
    - cron: '0 14 * * *'  # 11 AM Argentina
    - cron: '0 21 * * *'  # 18 PM Argentina
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install twikit==1.4.7

      - name: Ejecutar Bot
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_EMAIL: ${{ secrets.X_EMAIL }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
        run: python bot.py
