name: Bot Diario Violeta

on:
  schedule:
    - cron: '0 14 * * *'  # Las 11 AM de Argentina
    - cron: '0 21 * * *'  # Las 18 PM de Argentina
  workflow_dispatch:      # Permite que tú le des al botón cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install twikit

      - name: Ejecutar Bot
        env:
          X_USERNAME: ${{ secrets.X_USERNAME }}
          X_EMAIL: ${{ secrets.X_EMAIL }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
        run: python bot.py
